server:
  port: 8080
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: gateway-service
#          uri: https://www.jd.com/
#          predicates:
#            - Path=/

